name: ams
description: "A desktop application for managing apartment buildings."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.2

# List of packages, libraries, and tools that the project depends on
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  # firebase_auth: ^5.0.0
  # cloud_firestore: ^5.2.0
  # firebase_core: ^3.3.0
  http: ^1.0.0
  flutter_secure_storage: ^9.0.0
  intl: ^0.17.0
  animated_sidebar: ^1.0.0

# List of packages that the project depends on for development
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/langs/en.json
    - assets/langs/vi.json
